### ISSUE TITLE
Arduino UNO - Crc error

### ISSUE THREAD

**Issue by Fede717** [HydroSense/sensirion#2]
Hi! I'm trying to get working a Davis 7346 board with installed a SHT31-LSS with an Arduino uno, but i get "cry error"; could someone help me? I've successfully attached the datapin to A4 and clock pin to A5 and powered it with a 3.3v source, but no luck....

**Comment by amm042** [comment]
Hello, I haven't used this code in years. You might want to search around for other libraries, something else may exist. Sorry.
